version: "3"
services:
  server-api-getaway:
    build:
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - db
      - redis
    ports:
      - "7100:7100"
    volumes:
      - ./:/usr/src/app/server-api-gateway
    env_file: .env

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "3337:5432"

  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
